name: On merge changeset

on:
  pull_request:
    types: [closed]
    branches:
      - 'main'

jobs:
  publish:
    if: contains(github.event.pull_request.head.ref, 'changeset-release')

    name: 'Upload script'
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Bundle the script into a single file
        run: deno task build

      - name: Publish the script to Bunny
        uses: BunnyWay/actions/deploy-script@deploy-script@0.2.0
        with:
          script_id: ${{ secrets.SCRIPT_ID }}
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          file: "dist/index.ts"
